package compositekey;
// Generated Apr 2, 2015 2:25:18 PM by Hibernate Tools 4.3.1



/**
 * CompositetestingId generated by hbm2java
 */
public class CompositetestingId  implements java.io.Serializable {


     private String name;
     private String fname;

    public CompositetestingId() {
    }

    public CompositetestingId(String name, String fname) {
       this.name = name;
       this.fname = fname;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompositetestingId) ) return false;
		 CompositetestingId castOther = ( CompositetestingId ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getFname()==castOther.getFname()) || ( this.getFname()!=null && castOther.getFname()!=null && this.getFname().equals(castOther.getFname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getFname() == null ? 0 : this.getFname().hashCode() );
         return result;
   }   


}


